[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["ffmpeg"]

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --chdir backend server:app"
restartPolicyType = "on_failure"